hw 2-1, no bonus task
ZamKaf/2018-FS-11-Frontend-Chadov pull request #10
Opened 2019-03-21 22:24 UTC by ZamKaf

Штош.
Начало положено.
Там чтобы работало надо залогиниться любыми данными которые форму устроят (типа не меньше 8 символов)
Потом можно список чатов тыкать
К бэку это не привязано, но замокано, что список чатов подгружается при логине
Сделана клавиатура из 4 смайликов, вставляются в поле, вставляются в сообщение при отправке

2019-03-23 14:45 UTC, martinkomitsky commented on src/components/Messages/styles.module.css
> +	background: url('../../icons/sent.png?sprite');
![image](https://user-images.githubusercontent.com/14847018/54867629-7598f300-4d93-11e9-99f9-2fd7b4a5844a.png)
Это не работает

2019-03-23 14:47 UTC, martinkomitsky requested changes
Исправить замечания, подключить спрайт лоадер, исправить ошибки линтера
![image](https://user-images.githubusercontent.com/14847018/54867657-c6a8e700-4d93-11e9-82a7-bb1dcf998cf2.png)

2019-03-23 14:47 UTC, martinkomitsky commented on src/components/Messages/Form/Smiles/SmileButton/styles.module.css
> +    background: url(../../../../../icons/smiles.png) no-repeat;
Эти стили написаны вручную, хотя надо было пользоваться спрайт генератором. Спрайт взят готовый, что не выполняет пункт из дз

2019-03-23 16:52 UTC, ZamKaf commented
Обновлено

2019-03-25 07:46 UTC, martinkomitsky commented
Я так полагаю, ты не будешь делать пункт про спрайт лоадер?

2019-03-27 21:48 UTC, ZamKaf commented
Затянулось в итоге, но вот. Кажется, то, что нужно

2019-03-29 11:16 UTC, martinkomitsky approved these changes
Ура, с этим дз покончили. Не забывай git pull origin master в ветке дз 2

2019-03-29 11:16 UTC, merged

2019-03-29 11:17 UTC, martinkomitsky commented
6