Hw2 6
ZamKaf/2018-FS-11-Frontend-Chadov pull request #14
Opened 2019-04-18 19:30 UTC by ZamKaf

hw6

2019-04-19 08:53 UTC, chexex reviewed
Вижу два классовых компонента, переписанных на новые функциональные компоненты. Спасибо за работу

2019-04-19 08:53 UTC, chexex commented on src/components/Messages/Form/Smiles/JustButton/index.js
> +export default JustButton;
можно сократить до 
```js
export default (props) => {
  // ...
  // code goes here
  // ...
}
```

2019-04-19 08:53 UTC, chexex commented on src/components/Messages/Form/Smiles/SmileButton/index.js
> +    return (
Можно сократить до 
```js
const SmileButton = (props) => (
  <button
     // ... some code
   />
)
```

2019-04-19 08:53 UTC, chexex commented on src/components/Messages/Form/Smiles/index.js
> +        return (
```js
export default (props) => (
  <div>
    // ... some code
  </div>
)
```

2019-04-19 15:32 UTC, martinkomitsky requested changes
Исправить замечания

2019-04-21 22:16 UTC, ZamKaf commented
@martinkomitsky 
@chexex 
поправил

2019-04-22 14:53 UTC, martinkomitsky approved these changes

2019-04-22 14:54 UTC, merged

2019-04-22 14:54 UTC, martinkomitsky commented
10 плюс бонус