Hw2 7
ZamKaf/2018-FS-11-Frontend-Chadov pull request #15
Opened 2019-04-18 22:08 UTC by ZamKaf

Вроде и правда не трудно )

2019-04-19 15:33 UTC, martinkomitsky commented on src/App.test.js
>  import React from 'react';
Можно весь файл удалить

2019-04-19 15:35 UTC, martinkomitsky commented on src/components/Messages/utility/sizes.js
> +}
а ты проверял, что функция выводит при передаче отрицательных значений?)) допиши ветку, чтобы тоже возвращало false, и еще тест дополнительный на этот случай

2019-04-19 15:36 UTC, martinkomitsky requested changes
Исправить замечания

2019-04-21 22:15 UTC, ZamKaf commented
@martinkomitsky 
поправил

2019-04-22 14:54 UTC, martinkomitsky commented
@ZamKaf синкни с мастером, плиз

2019-04-22 16:20 UTC, martinkomitsky approved these changes

2019-04-22 16:20 UTC, merged

2019-04-22 16:21 UTC, martinkomitsky commented
10 и бонус