Hw5
ZamKaf/2018-FS-11-Frontend-Chadov pull request #6
Opened 2018-11-08 02:13 UTC by ZamKaf

Старый проект вообще целиком стёрт
Подключен к проекту Create React App
Переписаны компоненты на React
Восстановлены стили для всех компонентов

Спасибо за скринкаст )

2018-11-10 15:05 UTC, martinkomitsky commented
>Спасибо за скринкаст

Пжалст)

2018-11-10 16:12 UTC, martinkomitsky requested changes
Окей, только:
1. Не понял, зачем сообщения оборачивать в форму. Пусть будет div, что ли.
![image](https://user-images.githubusercontent.com/14847018/48303550-6d46c680-e51c-11e8-8947-9f6e470c8731.png)

2. Долго не мог понять, где писать сообщения - оформи как-нибудь в css. 
3. Пропали фичи загрузки файлов, геолокации и т.д.
4. Проект находится в папке project. Вынеси в корень, незачем иметь лишние уровни

2018-11-14 23:17 UTC, ZamKaf commented
1) Переделал
2) Переделал
3) Ну, что-то переделал) Геолокация изначально была необязательным так что её нету. Загрузка файлов у меня по нажатию пустого пространства справа от формы ввода :) Отправка по энтеру - только надо на форму ввода сначала тыкнуть, а то он снова файл предложит загрузить :\ Не очень юзерфрендли выходит, но времени чёто совсем нет :(
4) Переделал

2018-11-17 12:32 UTC, martinkomitsky approved these changes

2018-11-17 12:32 UTC, merged

2018-11-17 12:35 UTC, martinkomitsky commented
Круто!
10
Только исправь это, key должен быть уникальным, если это какой-то списочный компонент, то можно присваивать элементам индексы массива (если речь о `.map(val, ind) => <div key={ ind }>...`), иначе станет 5)
И, желательно, восстановить предыдущие функции - у меня не получилось просмотреть превью фото.
![image](https://user-images.githubusercontent.com/14847018/48661113-04ac9c00-ea7e-11e8-88d2-88cd8f54ab94.png)